# Generated by Django 4.2 on 2023-04-14 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, default='', null=True)),
                ('protagonists', models.TextField(blank=True, default='', null=True)),
                ('poster', models.TextField(blank=True, default='', null=True)),
                ('started_at', models.DateField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(1, 'upcoming'), (2, 'starting'), (3, 'running'), (4, 'finished')])),
                ('ranking', models.IntegerField(default=0)),
            ],
        ),
    ]
