# Generated by Django 4.2 on 2023-04-18 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='started_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
