MOVIE_STATUS_UPCOMING = 1
MOVIE_STATUS_STARTING = 2
MOVIE_STATUS_RUNNING = 3
MOVIE_STATUS_FINISHED = 4

MOVIE_STATUS = [
    (MOVIE_STATUS_UPCOMING, 'upcoming'),
    (MOVIE_STATUS_STARTING, 'starting'),
    (MOVIE_STATUS_RUNNING, 'running'),
    (MOVIE_STATUS_FINISHED, 'finished')
]
